// Copyright 2025 MongoDB, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use crate::{ffi, ffi_util::to_cpath, Error, ReadOptions};

use libc::{c_char, size_t};
use std::{marker::PhantomData, path::Path, slice};

/// SstFileReader is used to read SST files that are generated by DB or SstFileWriter.
pub struct SstFileReader<'a> {
    pub(crate) inner: *mut ffi::rocksdb_sstfilereader_t,
    phantom: PhantomData<&'a crate::Options>,
}

unsafe impl Send for SstFileReader<'_> {}
unsafe impl Sync for SstFileReader<'_> {}

impl<'a> SstFileReader<'a> {
    /// Creates a new SstFileReader with the given options.
    pub fn create(opts: &'a crate::Options) -> Self {
        let inner = unsafe { ffi::rocksdb_sstfilereader_create(opts.inner) };
        Self {
            inner,
            phantom: PhantomData,
        }
    }

    /// Opens an SST file at the given path for reading.
    pub fn open<P: AsRef<Path>>(&self, path: P) -> Result<(), Error> {
        let cpath = to_cpath(&path)?;
        unsafe {
            ffi_try!(ffi::rocksdb_sstfilereader_open(self.inner, cpath.as_ptr(),));
        }
        Ok(())
    }

    /// Returns a new iterator over the SST file contents.
    ///
    /// The caller must call `seek_to_first()`, `seek_to_last()`, or `seek(key)`
    /// before reading any data.
    pub fn new_iterator(&self, readopts: &ReadOptions) -> SstFileReaderIterator {
        let inner =
            unsafe { ffi::rocksdb_sstfilereader_new_iterator(self.inner, readopts.inner) };
        SstFileReaderIterator { inner }
    }

    /// Verifies the checksums of all blocks in the SST file.
    pub fn verify_checksum(&self) -> Result<(), Error> {
        unsafe {
            ffi_try!(ffi::rocksdb_sstfilereader_verify_checksum(self.inner,));
        }
        Ok(())
    }
}

impl Drop for SstFileReader<'_> {
    fn drop(&mut self) {
        unsafe {
            ffi::rocksdb_sstfilereader_destroy(self.inner);
        }
    }
}

/// An iterator over the contents of an SST file, returned by
/// [`SstFileReader::new_iterator`].
pub struct SstFileReaderIterator {
    inner: *mut ffi::rocksdb_iterator_t,
}

unsafe impl Send for SstFileReaderIterator {}
unsafe impl Sync for SstFileReaderIterator {}

impl SstFileReaderIterator {
    /// Returns `true` if the iterator is valid.
    pub fn valid(&self) -> bool {
        unsafe { ffi::rocksdb_iter_valid(self.inner) != 0 }
    }

    /// Returns the status of the iterator. If the iterator encountered an error,
    /// returns `Err`.
    pub fn status(&self) -> Result<(), Error> {
        unsafe {
            ffi_try!(ffi::rocksdb_iter_get_error(self.inner,));
        }
        Ok(())
    }

    /// Seeks to the first key in the SST file.
    pub fn seek_to_first(&mut self) {
        unsafe {
            ffi::rocksdb_iter_seek_to_first(self.inner);
        }
    }

    /// Seeks to the last key in the SST file.
    pub fn seek_to_last(&mut self) {
        unsafe {
            ffi::rocksdb_iter_seek_to_last(self.inner);
        }
    }

    /// Seeks to the specified key or the next key if the given key does not exist.
    pub fn seek(&mut self, key: &[u8]) {
        unsafe {
            ffi::rocksdb_iter_seek(
                self.inner,
                key.as_ptr() as *const c_char,
                key.len() as size_t,
            );
        }
    }

    /// Seeks to the specified key or the previous key if the given key does not
    /// exist.
    pub fn seek_for_prev(&mut self, key: &[u8]) {
        unsafe {
            ffi::rocksdb_iter_seek_for_prev(
                self.inner,
                key.as_ptr() as *const c_char,
                key.len() as size_t,
            );
        }
    }

    /// Advances the iterator to the next key.
    pub fn next(&mut self) {
        unsafe {
            ffi::rocksdb_iter_next(self.inner);
        }
    }

    /// Moves the iterator to the previous key.
    pub fn prev(&mut self) {
        unsafe {
            ffi::rocksdb_iter_prev(self.inner);
        }
    }

    /// Returns the current key, or `None` if the iterator is invalid.
    pub fn key(&self) -> Option<&[u8]> {
        if self.valid() {
            let mut key_len: size_t = 0;
            let key_ptr =
                unsafe { ffi::rocksdb_iter_key(self.inner, &mut key_len) as *const u8 };
            Some(unsafe { slice::from_raw_parts(key_ptr, key_len) })
        } else {
            None
        }
    }

    /// Returns the current value, or `None` if the iterator is invalid.
    pub fn value(&self) -> Option<&[u8]> {
        if self.valid() {
            let mut val_len: size_t = 0;
            let val_ptr =
                unsafe { ffi::rocksdb_iter_value(self.inner, &mut val_len) as *const u8 };
            Some(unsafe { slice::from_raw_parts(val_ptr, val_len) })
        } else {
            None
        }
    }
}

impl Drop for SstFileReaderIterator {
    fn drop(&mut self) {
        unsafe {
            ffi::rocksdb_iter_destroy(self.inner);
        }
    }
}
